CCOMPILE=tile-gcc

PLATFORM_CFLAGS = -O3 
PLATFORM_LDFLAGS = -ltmc
PLATFORM_LIBS = 
PLATFORM_DEFINES = -DPLATFORM_TILERA \
                   -DDSL \
                   -DPGAS \
                   -DREAD_BUF_OFF \
                   -UDEBUG_UTILIZATION \
                   -UDO_TIMINGS \
                   -DBACKOFF \
                   -UDISABLE_CC

ARCHIVE_SRCS_PURE+=sys_TILERA.c
