#!/bin/sh

if [ $# -lt 3 ]; then
    echo "Usage: runavg GREP_PATTERN FIELD_TO_KEEP PROGRAM [PARAMETERS] [PARAMETERSinsteadofcores] [numcores]";
    echo "ex. ./runavg \"ticks/msg\" 1 bmarks/mp";
else
    pattern=$1;
    shift;
    field=$1;
    shift;
    prog=$1;
    shift;

    for nue in 2 4 8 16 32 48; do
	printf "$nue \t";
	./run  $nue $prog $@ | grep "$pattern" | awk -v fl=$field '// {sum+=$fl}; END {print sum/NR}'
	
    done
fi

exit