#!/bin/sh

repetitions=3;
out="out.runrrep";
cores="2 4 8 16 32 48";

if [ $(uname -n) = "parsasrv1.epfl.ch" ];
then
cores="2 4 8 16 32 36";
fi;

if [ -f  $out ]; then
    rm $out;

fi


if [ $# -lt 2 ]; then
    echo "Usage: runrrep REPETITIONS PROGRAMS [PARAMETERS] [PARAMETERSinsteadofcores] [numcores]";
    echo "";
    echo "run repeatedly (from 2..48 cores) using many (default $repetitions) repetitions;";
    echo "output can be collected using collect[.].awk from $out file";
else
    repetitions=$1;
    if [ $# -lt 4 ]; then
	for nue in $cores; 
	do
	    echo $nue
	    for prog in $2; 
	    do
		echo $prog " " $3;
		./runrep_ $prog $nue $repetitions $3 >> $out;
	    done
	done
    else
	nue=48;
	if [ $# -gt 3 ]; then
	    nue=$4;
	fi

	for par in $3; do
	    echo $par
	    for prog in $2; do
		echo $prog
		screen -L ./run $nue rc.hosts ./$prog $1 $par;
	    done
	done
    fi
fi

exit

